# Generated by Django 5.2.7 on 2025-10-05 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDoctorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for assignment or medical condition', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the assignment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_mappings', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_mappings', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_mappings', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient-Doctor Mapping',
                'verbose_name_plural': 'Patient-Doctor Mappings',
                'db_table': 'patient_doctor_mappings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='patient_doc_patient_b4bfb7_idx'), models.Index(fields=['doctor', 'status'], name='patient_doc_doctor__4c21b2_idx'), models.Index(fields=['created_by'], name='patient_doc_created_cc70d9_idx'), models.Index(fields=['assigned_date'], name='patient_doc_assigne_ddfdfc_idx')],
                'unique_together': {('patient', 'doctor')},
            },
        ),
    ]
